# -*- coding: utf-8 -*-
"""Etched Take-Home Multiplier Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzVixtYtFbxafuuih49Lif2twmWzYDNC
"""

!pip install ml-dtypes==0.5.1
import itertools
import numpy as np
import ml_dtypes
assert ml_dtypes.__version__ == "0.5.1"
from ml_dtypes import uint4, float4_e2m1fn
from numpy import float32, int16
from typing import List, Dict

# Valid operations - do NOT modify this. For simplicity, each costs the
# same amount.
NOT = lambda x: not x
OR = lambda x, y: x | y
AND = lambda x, y: x & y
XOR = lambda x, y: x ^ y

# Example remapping showing how you can use 0b0000 for both +0 and -0, if you like

# We MAY ALSO swap items around - instead of 1.5 being 0b0011 and 1 being 0b0010,
# you could swap these we could make it so that 1 was 0b0011 and 1.5 was 0b0010.

INPUT_REMAP = {
    float4_e2m1fn(0):    uint4(0b0000),
    float4_e2m1fn(0.5):  uint4(0b0001),
    float4_e2m1fn(1):    uint4(0b0010),
    float4_e2m1fn(1.5):  uint4(0b0011),
    float4_e2m1fn(2):    uint4(0b0100),
    float4_e2m1fn(3):    uint4(0b0101),
    float4_e2m1fn(4):    uint4(0b0110),
    float4_e2m1fn(6):    uint4(0b0111),
    float4_e2m1fn(-0.0): uint4(0b0000),
    float4_e2m1fn(-0.5): uint4(0b1001),
    float4_e2m1fn(-1):   uint4(0b1010),
    float4_e2m1fn(-1.5): uint4(0b1011),
    float4_e2m1fn(-2):   uint4(0b1100),
    float4_e2m1fn(-3):   uint4(0b1101),
    float4_e2m1fn(-4):   uint4(0b1110),
    float4_e2m1fn(-6):   uint4(0b1111),
}

# You must use the same remapping scheme for both inputs (as using different
# remapping schemes for the two inputs does not shrink the circuit). You may NOT
# remap the output values (because this would make it take more microchip area
# to add the output values).

# This circuit has SEVEN gates, but gives the wrong result in many cases.
# Your job is to replace this with an optimal circuit.

def write_your_multiplier_here(a0, a1, a2, a3, b0, b1, b2, b3):
    # a0 is sign bit, a1 + a2 are exponent bit, a3 is mantissa bit
    res0 = XOR(a0, b0)
    res1 = XOR(res0, AND(a1, AND(a1, AND(a3, AND(b1, AND(b2, b3))))))

    res2 = False
    res3 = False
    res4 = False
    res5 = False
    res6 = False
    res7 = False
    res8 = False

    # res0 is most significant bit in two's complement. res8 is least significant
    # bit (with place value 1/4th)
    return res0, res1, res2, res3, res4, res5, res6, res7, res8

def format_fp4(fp4: float4_e2m1fn):
    return f"0b{int(fp4.view(uint4)):04b}"

def format_qi9(qi9: np.int16):
    upper_bits = qi9 & np.int16(-2**9)
    lower_bits = qi9 & np.int16(2**9 - 1)
    assert upper_bits == np.int16(-2**9) or upper_bits == np.int16(0)
    return f"0b{qi9 & lower_bits:09b}"

def fp4_to_list_of_bits(fp4: float4_e2m1fn):
    uint_value = int(fp4.view(uint4))
    return [(uint_value >> i) & 1 for i in reversed(range(4))]

# Examples
assert fp4_to_list_of_bits(float4_e2m1fn(0)) == [False, False, False, False]
assert fp4_to_list_of_bits(float4_e2m1fn(0.5)) == [False, False, False, True]
assert fp4_to_list_of_bits(float4_e2m1fn(-6)) == [True, True, True, True]


for a in range(0, 2**4):
    for b in range(0, 2**4):
        a_fp4: float4_e2m1fn = uint4(a).view(float4_e2m1fn)
        b_fp4: float4_e2m1fn = uint4(b).view(float4_e2m1fn)
        print(f"Multiplying {a_fp4} (FP4: {format_fp4(a_fp4)}) * {b_fp4} (FP4: {format_fp4(b_fp4)})")

        # Compute reference result
        expected_fp32 = a_fp4.astype(float32) * b_fp4.astype(float32)
        expected_qi9 = np.int16(np.round(expected_fp32 * 4))
        print(f"Expected result: {expected_fp32} (QI9: {format_qi9(expected_qi9)})")


        # Compute actual result, including using the remap
        a_bits = fp4_to_list_of_bits(INPUT_REMAP[a_fp4])
        b_bits = fp4_to_list_of_bits(INPUT_REMAP[b_fp4])
        actual_result_bits = write_your_multiplier_here(*a_bits, *b_bits)
        actual_result_qi9 = np.uint16(sum(bit << (8 - i) for i, bit in enumerate(actual_result_bits)))
        if actual_result_bits[0]: actual_result_qi9 += np.uint16(0b1111111000000000)
        actual_result_qi9 = actual_result_qi9.view(np.int16)

        actual_result_fp32 = float32(actual_result_qi9) * 0.25
        print(f"Actual result: {actual_result_fp32} (QI9: {format_qi9(actual_result_qi9)})")
        print()

        assert expected_qi9 == actual_result_qi9, "Actual result is not correct!"